config/routes.rb
Rails.application.routes.draw do
  root to: "agents#random_agent"

  resources :agents do
    resources :uploaded_transactions do
      collection {post :import}
    end
  end
end

app/models/agent.rb
class Agent < ApplicationRecord
  has_many :uploaded_seller_transactions, class_name: "UploadedTransaction", foreign_key: :listing_agent_id
  has_many :uploaded_buyer_transactions, class_name: "UploadedTransaction", foreign_key: :selling_agent_id

  def all_transactions 
    UploadedTransaction.where("listing_agent_id = ? OR selling_agent_id = ?", id, id)#.paginate(:page => page,:per_page => 3).order('id DESC')
  end

  def recent_transactions
    all_transactions.where("selling_date > ?", 6.months.ago)
  end

  def full_name
    "#{first_name} #{last_name}"
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/uploaded_transaction.rb
class UploadedTransaction < ApplicationRecord
  belongs_to :listing_agent, required: false, class_name: "Agent"
  belongs_to :selling_agent, required: false, class_name: "Agent"

  scope :single_family_homes, -> { where(property_type: "single_family_home") }
  scope :sold, -> { where(status: "sold") }

  def full_address
    "#{address}, #{city}, #{state} #{zip}"
  end
  
  def self.dedup
    columns = [:zip, :address, :selling_date]
    ids = UploadedTransaction.order('created_at ASC').select("#{columns.join(',')}, COUNT(*)").group(columns).having("COUNT(*) > 1").pluck(:id)
    UploadedTransaction.where(id: ids).destroy_all
  end
  
  def self.import(file)
    CSV.foreach(file.path, headers: true) do |row|
      puts row
      UploadedTransaction.create! row.to_hash
    end
    UploadedTransaction.dedup
  end
  
  def self.to_csv
    attributes = UploadedTransaction.attribute_names - ["created_at", "updated_at", "id"]
    CSV.generate(headers: true) do |csv|
      csv << attributes
      all.each do |user|
        csv << attributes.map{ |attr| user.send(attr) }
      end
    end
  end
  
end

app/controllers/agents_controller.rb
class AgentsController < ApplicationController
  def show
    @agent = Agent.find(params[:id])
    @uploaded_transactions = @agent.all_transactions.paginate(:page => params[:page], :per_page => 4)
    respond_to do |format|
      format.html
      format.csv { send_data @uploaded_transactions.to_csv, filename: "TRANSACTIONS-#{Date.today}.csv" }
    end
  end

  def random_agent
    redirect_to agent_path(Agent.all.sample)
  end
  
end

# @uploaded_transactions = @agent.all_transactions
# UploadedTransaction.attribute_names

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/uploaded_transactions_controller.rb
class UploadedTransactionsController < ApplicationController
  def new
    @agent = Agent.find(params[:agent_id])
    @uploaded_transaction = @agent.uploaded_seller_transactions.new
  end
  
  def create
    agent = Agent.find(params[:agent_id])
    uploaded_transaction = agent.uploaded_seller_transactions.create(uploaded_transaction_params)

    if uploaded_transaction.save
      redirect_to agent_path(agent), notice: "Transaction saved!"
    else
      render "new"
    end
  end
  
  def import
    UploadedTransaction.import(params[:file])
    redirect_to root_path, notice: "Transactions uploaded succesfully!"
  end
  
  private

  def uploaded_transaction_params
    params.require(:uploaded_transaction).permit(:address, :city, :state, :zip, :listing_agent, :listing_price, :listing_date, :selling_price, :selling_agent, :selling_date, :status, :property_type)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/agents/show.html.slim
div 

h1 = @agent.full_name
p = @agent.bio

table.table-sm
  thead
    tr
      th Filter
      th Action
      th
  tbody
    tr
      = form_tag import_agent_uploaded_transactions_path(@agent), multipart: true do
      td = file_field_tag :file
      td = submit_tag "Bulk Upload Transactions", class: "btn btn-primary"
    tr  
      td
      td = link_to "Add Single Transaction", new_agent_uploaded_transaction_path(@agent), class: "btn btn-primary"
    tr  
      td
      td = link_to "Download Transactions ", agent_path(@agent, :format => "csv"), class: "btn btn-primary"

h3 Recent Transactions         
table.table-striped.table-hover.table-sm
  thead
    tr
      th Age
      th Address
      th Listed
      th Listing Price
      th Sold
      th Selling Price
      th
  tbody
    - @uploaded_transactions.each do |uploaded_transaction|
      tr
        td = time_ago_in_words(uploaded_transaction.created_at, include_seconds: true)
        td = truncate(uploaded_transaction.full_address, :length => 44)
        td = uploaded_transaction.listing_date
        td = uploaded_transaction.listing_price
        td = uploaded_transaction.selling_date
        td = uploaded_transaction.selling_price
        

    
.apple_pagination
  .page_info
    = page_entries_info @uploaded_transactions
  = will_paginate @uploaded_transactions, :container => false

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Uploaded Transactions Manager</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbolinks-track": "reload" %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="container">
        <a class="navbar-brand" href="#">HomeLight</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
             <li class="nav-item dropdown active">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Agents</a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                <% Agent.all.each do |agent| %>
                  <a class="dropdown-item" href="<%= agent_path(agent) %>"><%= agent.full_name %></a>
                <% end %>
              </div>
            </li>
          </ul>
        </div>
      </div>
    </nav>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/uploaded_transactions/new.html.slim
h1 New Transaction

= form_for [@agent, @uploaded_transaction] do |f|
  .form-group
    = f.label :address
    = f.text_field :address, class: "form-control"
  .form-group
    = f.label :city
    = f.text_field :city, class: "form-control"
  .form-group
    = f.label :state
    = f.text_field :state, class: "form-control"
  .form-group
    = f.label :zip
    = f.text_field :zip, class: "form-control"
  .form-group
    = f.label :listing_date
    = f.text_field :listing_date, class: "form-control"
  .form-group
    = f.label :listing_price
    = f.text_field :listing_price, class: "form-control"
  .form-group
    = f.label :selling_date
    = f.text_field :selling_date, class: "form-control"
  .form-group
    = f.label :selling_price
    = f.text_field :selling_price, class: "form-control"
  .form-group
    = f.label :status
    = f.select :status, %w(sold pending closed cancelled expired active)
  .form-group
    = f.label :property_type
    = f.select :property_type, %w(condo single_family_home multi_family_home commercial mobile_home land)

  = f.submit "Save", class: "btn btn-primary"